ci: updated workflow file

diff --git a/.github/workflows/build_and_test.yaml b/.github/workflows/build_and_test.yaml
--- a/.github/workflows/build_and_test.yaml
+++ b/.github/workflows/build_and_test.yaml
@@ -5,7 +5,8 @@ on:
     branches: [main]
 
 env:
-  DEEPSOURCE_CLI_VERSION: v0.8.6
+  DEEPSOURCE_CLI_VERSION: 0.8.6
+  GOLANG_VERSION: 1.21
 
 jobs:
   build-and-test:
@@ -18,12 +19,30 @@ jobs:
         run: |
           rustup update stable
           cargo +stable install cargo-llvm-cov
-      - name: Prepare Golang Toolchain
-        uses: actions/setup-go@v5
-        with:
-          go-version: 1.21
-      - name: Build DeepSource CLI
-        run: go install github.com/deepsourcelabs/cli/cmd/deepsource@${{ env.DEEPSOURCE_CLI_VERSION }}
+      # Note that amd64 in Golang should
+      # convert to x86_64
+      - name: Download DeepSource CLI
+        run: |
+          OS=$(go env GOOS)
+          ARCH=$(go env GOARCH)
+          # convert amd64 to x86_64
+          if [ "$ARCH" = "amd64" ]; then
+            ARCH="x86_64"
+          fi
+          PLATFORM="${OS}_${ARCH}"
+          echo "Downloading DeepSource CLI for $PLATFORM on version v$DEEPSOURCE_CLI_VERSION"
+          gh release download v$DEEPSOURCE_CLI_VERSION -R DeepSourceCorp/cli --pattern "*$PLATFORM.tar.gz"
+          tar -xvzf "deepsource_${DEEPSOURCE_CLI_VERSION}_${PLATFORM}.tar.gz"
+          IS_DEEPSOURCE_CLI_DOWNLOADED=$(ls -1 | grep deepsource | wc -l)
+          if [ "$IS_DEEPSOURCE_CLI_DOWNLOADED" -eq 0 ]; then
+            echo "DeepSource CLI download failed"
+            exit 1
+          else
+            echo "DeepSource CLI downloaded successfully"
+          fi
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          DEEPSOURCE_CLI_VERSION: ${{ env.DEEPSOURCE_CLI_VERSION }}
       - name: Checkout Code
         uses: actions/checkout@v4
         if: ${{ github.event_name != 'pull_request' }}
@@ -39,6 +58,6 @@ jobs:
       - name: Check Coverage
         run: cargo +stable llvm-cov --lcov --output-path coverage.info
       - name: Upload Coverage
-        run: deepsource report --analyzer test-coverage --key rust --value-file coverage.info
+        run: ./deepsource report --analyzer test-coverage --key rust --value-file coverage.info
         env:
           DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
